{
 "title": "Fake router showcase",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Fake Router",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{filename=~\"/var/lib/docker/containers/b9048867bcfd404f80a91b63a3f445a58f31816eb531d7b665b70696a9117b04/b9048867bcfd404f80a91b63a3f445a58f31816eb531d7b665b70696a9117b04-json\\\\.log|/var/lib/docker/containers/f4d157656797e99c244dbcfa7c6fbfd7a9c7a9ff2770d669bc355e75586a65a3/f4d157656797e99c244dbcfa7c6fbfd7a9c7a9ff2770d669bc355e75586a65a3-json\\\\.log\"}"
    }
   ]
  },
  {
   "title": "Sniffer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{filename=\"/var/lib/docker/containers/b40974000c474019d200d5487f2c00b1e1505bb53de48ac5bf89123c7cfc8d0d/b40974000c474019d200d5487f2c00b1e1505bb53de48ac5bf89123c7cfc8d0d-json.log\"}"
    }
   ]
  },
  {
   "title": "Host logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{filename=\"/var/log/host_operations.log\"}"
    }
   ]
  }
 ]
}